### ISSUE TITLE
Create an html page with login button

### ISSUE THREAD

**Issue by ParthasarathiPanda** [ParthasarathiPanda/Login-form#1]
Create an html page with login button, should looks like below.

![image](https://github.com/ParthasarathiPanda/Login-form/assets/97597630/c003f9d1-0ddf-4a3e-9598-6fb53fa14c18)

**Comment by ParthasarathiPanda** [comment]
Parthasarathi@SNP will work on it

**Comment by Partha-2000-Snp** [comment]
Working on it

**Comment by ParthasarathiPanda** [comment]
marged

**Comment by ParthasarathiPanda** [comment]
completed
